### ISSUE TITLE
Startup fails on module loading error

### ISSUE THREAD

**Issue by eis** [eis/wildfly-swarm-example#2]
`$ mvn wildfly-swarm:run`

```
Exception in thread "main" java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xalan/main/module.xml
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:89)
	at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:684)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:677)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:487)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:390)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1354)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addPaths(Module.java:1246)
	at org.jboss.modules.Module.link(Module.java:1573)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1601)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
	at org.wildfly.swarm.bootstrap.MainInvoker.getMainClass(MainInvoker.java:112)
	at org.wildfly.swarm.bootstrap.MainInvoker.main(MainInvoker.java:101)
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xalan/main/module.xml
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:298)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:65)
	... 14 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'xalan:serializer:2.7.1.jbossorg-4' (position: END_TAG seen ...esources>\n    <artifact name="xalan:serializer:2.7.1.jbossorg-4"/>... @5:57) 
	at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:953)
	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:854)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:645)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:416)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:296)
```

**Comment by eis** [comment]
Seems to be https://issues.jboss.org/browse/THORN-1216

**Comment by eis** [comment]
For some reason not getting this anymore, and not able to reproduce. Local maven repo issue?

**Comment by eis** [comment]
Am able to reproduce again using clean repo 

```
$ mvn -Dmaven.repo.local=/tmp/mvn-repository clean wildfly-swarm:run
```

```
Sat Jun 09 12:47:32 EEST 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
Exception in thread "main" java.lang.RuntimeException: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xalan/main/module.xml
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:89)
	at org.jboss.modules.ModuleLoader.findModule0(ModuleLoader.java:684)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:677)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:487)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:390)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1354)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addExportedPaths(Module.java:1402)
	at org.jboss.modules.Module.addPaths(Module.java:1246)
	at org.jboss.modules.Module.link(Module.java:1573)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1601)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:287)
	at org.wildfly.swarm.bootstrap.MainInvoker.getMainClass(MainInvoker.java:112)
	at org.wildfly.swarm.bootstrap.MainInvoker.main(MainInvoker.java:101)
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from modules/org/apache/xalan/main/module.xml
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:298)
	at org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder.findModule(BootstrapClasspathModuleFinder.java:65)
	... 14 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact 'xalan:serializer:2.7.1.jbossorg-4' (position: END_TAG seen ...esources>\n    <artifact name="xalan:serializer:2.7.1.jbossorg-4"/>... @5:57) 
	at org.jboss.modules.xml.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:953)
	at org.jboss.modules.xml.ModuleXmlParser.parseResources(ModuleXmlParser.java:854)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:645)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:416)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:296)
```

**Comment by eis** [comment]
Similar issues:

 - https://issues.jboss.org/browse/THORN-542
 - https://issues.jboss.org/browse/THORN-1216
 - https://issues.jboss.org/browse/THORN-776

**Comment by eis** [comment]
It seems this issue happens for me when having:

```
<plugin>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>wildfly-swarm-plugin</artifactId>
    <version>${wildfly.version}</version>
    <executions>
        <execution>
            <id>package</id>
        </execution>
        <execution>
            <id>start</id>
        </execution>
        <execution>
            <id>stop</id>
        </execution>
    </executions>
</plugin>
```

and issuing wildfly-swarm:run, using a repo that hasn't had dependencies loaded yet.

If one changes configuration at least once to this:

```
<plugin>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>wildfly-swarm-plugin</artifactId>
    <version>${wildfly.version}</version>
    <executions>
        <execution>
            <id>package</id>
        </execution>
        <execution>
            <id>start</id>
        </execution>
        <execution>
            <id>stop</id>
        </execution>
        <execution>
          <goals>
            <goal>package</goal>
          </goals>
        </execution>
    </executions>
</plugin>
```

and then does mvn wildfly-swarm:run at least once, dependencies are downloaded to repo and it works hereafter, also without package execution block.

To reproduce the issue, try with empty repo:

`mvn clean wildfly-swarm:run -Dmaven.repo.local=/tmp/maven-temp-repo-3`

**Comment by eis** [comment]
<a href="https://github.com/eis/wildfly-swarm-example/tree/bug/module-loading">module-loading branch</a> demonstrates the issue.

**Comment by eis** [comment]
Reported: https://issues.jboss.org/browse/THORN-2080
