### ISSUE TITLE
Upgrading Wildfly breaks dependency mechanism

### ISSUE THREAD

**Issue by eis** [eis/wildfly-swarm-example#6]
Upgrading

```
<wildfly.version>2018.3.0</wildfly.version>
```
to

```
<wildfly.version>2018.4.0</wildfly.version>
```
or higher causes this:
```
2018-06-08 23:14:30,898 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.invoke(MainInvoker.java:53)
2018-06-08 23:14:30,898 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.MainInvoker.main(MainInvoker.java:106)
2018-06-08 23:14:30,898 ERROR [stderr] (main) Caused by: org.wildfly.swarm.container.DeploymentException: org.wildfly.swarm.container.DeploymentException: WFSWARM0004: Deployment failed: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"wildfly-swarm-example-1.0-SNAPSHOT.war\".WeldStartService" => "Failed to start service
2018-06-08 23:14:30,898 ERROR [stderr] (main)     Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 5 exceptions:
2018-06-08 23:14:30,898 ERROR [stderr] (main) Exception 0 :
2018-06-08 23:14:30,898 ERROR [stderr] (main) org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type DeploymentContext with qualifiers @Default
2018-06-08 23:14:30,898 ERROR [stderr] (main)   at injection point [BackedAnnotatedField] @Inject org.wildfly.swarm.container.runtime.cdi.configurable.DeploymentProducer.context

2018-06-08 23:14:30,900 ERROR [stderr] (main) Exception 2 :
2018-06-08 23:14:30,900 ERROR [stderr] (main) org.jboss.weld.exceptions.DeploymentException: WELD-001410: The injection point has non-proxyable dependencies: [BackedAnnotatedField] @Inject private org.wildfly.swarm.container.runtime.RuntimeDeployer.defaultDeploymentCreator

2018-06-08 23:14:30,901 ERROR [stderr] (main) Caused by: org.jboss.weld.exceptions.UnproxyableResolutionException: WELD-001435: Normal scoped bean class org.wildfly.swarm.container.runtime.deployments.DefaultDeploymentCreator is not proxyable because it has no no-args constructor - Managed Bean [class org.wildfly.swarm.container.runtime.deployments.DefaultDeploymentCreator] with qualifiers [@Any @Default].

```

**Comment by eis** [comment]
See <a href="https://github.com/eis/wildfly-swarm-example/tree/wildfly-update">wildfly update branch</a> for attempts to fix this.

**Comment by eis** [comment]
Discussed in https://stackoverflow.com/questions/50783081/updating-wildfly-swarm-version-breaks-dependency-injection
